#cloud-config
#package_update: true
#package_upgrade: true
packages:
  - iptables
  - iptables-nft-services
  - nmap-ncat
  - tmux
write_files:
- encoding: b64
  content: bmV0LmlwdjQuaXBfZm9yd2FyZCA9IDEKbmV0LmlwdjYuY29uZi5hbGwuZm9yd2FyZGluZyA9IDEKbmV0LmlwdjQuY29uZi5hbGwuc2VuZF9yZWRpcmVjdHMgPSAwCg==
  owner: root:root
  path: /etc/sysctl.d/mitmproxy.conf
  permissions: '0644'
runcmd:
- sysctl -p /etc/sysctl.d/mitmproxy.conf
- curl -s https://downloads.mitmproxy.org/10.3.0/mitmproxy-10.3.0-linux-x86_64.tar.gz -o - | tar -C /usr/bin/ -xzf -
- iptables -F
- iptables -X
- iptables -t nat -F
- iptables -t nat -X
- iptables -t mangle -F
- iptables -t mangle -X
- iptables -t raw -F
- iptables -t raw -X
- iptables -t security -F
- iptables -t security -X
- iptables -P INPUT ACCEPT
- iptables -P FORWARD ACCEPT
- iptables -P OUTPUT ACCEPT
- iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
- iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
- ip6tables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
- ip6tables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
- /sbin/iptables-save > /etc/sysconfig/iptables
- /sbin/ip6tables-save > /etc/sysconfig/ip6tables
- systemctl enable --now iptables
- tmux new-session -d -s mitmproxy '/usr/bin/mitmproxy --mode transparent --showhost'
- sleep 3 && cat ~/.mitmproxy/mitmproxy-ca-cert.pem | nc termbin.com 9999
- echo "Download the CA cert from the link above. To observe traffic flowing through the proxy, SSH-in and run 'sudo tmux attach -t mitmproxy'"
